#include<stdio.h>
#include<conio.h>

#define even(n) (n%2==0)

void main()
{
  int n;
  clrscr();
  printf("Enter a number: ");
  scanf("%d", &n);
  if even(n)
    printf("%d is an even number.", n);
  else
    printf("%d is an odd number.", n);
  getch();
}
/* OUTPUT
Enter a number: 10
10 is an even number.                                                           
Enter a number: 15
15 is an odd number.                                                            
                                                                                
	     */
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                

                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
