/*Sizeof and typecasting*/
#include<stdio.h>
#include<conio.h>
void main()
{
int n=5,*ptr;
clrscr();
ptr=&n;
printf("\nvalue of n=%f",float(n));
printf("\nafter type caste size of variable=%u",sizeof(n));
printf("\nsize of pointer=%u\n",sizeof(*ptr));
getch();
}
===================output=============

value of n=5.000000                                                             
after type caste size of variable=2                                             
size of pointer=2                                                               
                                                                                

                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
