#include<stdio.h>
#include<conio.h>

void main()
{
 clrscr();
 int a,b;
 float avg1, avg2;
 printf("Program to Find average of two numbers\nEnter two numbers:");
 scanf("%d %d",&a,&b);
 avg1=(float)(a+b)/2;
 avg2=(a+b)/2;
 printf("Without typecasting,\n\tAverage=%0.3f\nWith Typecasting,\n\tAverage=%0.3f", avg2,avg1);
 getch();
}
/*========OUTPUT========
Program to Find average of two numbers
Enter two numbers:3 4
Without typecasting,
	Average=3.000
With Typecasting,
	Average=3.500
*/

                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
